# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Check disk space
        shell: pwsh
        run: |
          $thresholdGB = 5
          $drive = Get-PSDrive -PSProvider FileSystem | Where-Object { $_.Name -eq "/" -or $_.Root -eq "/" }

          if (-not $drive) {
              $drive = Get-PSDrive -PSProvider FileSystem | Select-Object -First 1
          }

          $freeGB = [math]::Round($drive.Free / 1GB, 2)
          Write-Host "Disk check: $freeGB GB free"
          Write-Output "::notice::To be or not to be"

          if ($freeGB -lt $thresholdGB) {
              Write-Host "::error::Low disk space: $freeGB GB free"
              exit 1
          }

          $driveLetter = (Get-Location).Path.Substring(0,1)
          $drive = Get-PSDrive -Name $driveLetter
          $freeGB = [math]::Round($drive.Free / 1GB, 2)
          $totalGB = [math]::Round(($drive.Used + $drive.Free) / 1GB, 2)

          $summary = @"
          ### 💾 Disk Usage
          - Drive: $driveLetter
          - Free: **$freeGB GB**
          - Total: $totalGB GB
          "@

          $summary | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
          
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
